/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookNowRouteImport } from './routes/book-now'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OmkareshwarRouteImport } from './routes/omkareshwar'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as UjjainDarshanRouteImport } from './routes/ujjain-darshan'
import { Route as VehiclesRouteImport } from './routes/vehicles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookNowRoute = BookNowRouteImport.update({
  id: '/book-now',
  path: '/book-now',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OmkareshwarRoute = OmkareshwarRouteImport.update({
  id: '/omkareshwar',
  path: '/omkareshwar',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const UjjainDarshanRoute = UjjainDarshanRouteImport.update({
  id: '/ujjain-darshan',
  path: '/ujjain-darshan',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-now': typeof BookNowRoute
  '/contact': typeof ContactRoute
  '/omkareshwar': typeof OmkareshwarRoute
  '/services': typeof ServicesRoute
  '/ujjain-darshan': typeof UjjainDarshanRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-now': typeof BookNowRoute
  '/contact': typeof ContactRoute
  '/omkareshwar': typeof OmkareshwarRoute
  '/services': typeof ServicesRoute
  '/ujjain-darshan': typeof UjjainDarshanRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-now': typeof BookNowRoute
  '/contact': typeof ContactRoute
  '/omkareshwar': typeof OmkareshwarRoute
  '/services': typeof ServicesRoute
  '/ujjain-darshan': typeof UjjainDarshanRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book-now'
    | '/contact'
    | '/omkareshwar'
    | '/services'
    | '/ujjain-darshan'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book-now'
    | '/contact'
    | '/omkareshwar'
    | '/services'
    | '/ujjain-darshan'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book-now'
    | '/contact'
    | '/omkareshwar'
    | '/services'
    | '/ujjain-darshan'
    | '/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookNowRoute: typeof BookNowRoute
  ContactRoute: typeof ContactRoute
  OmkareshwarRoute: typeof OmkareshwarRoute
  ServicesRoute: typeof ServicesRoute
  UjjainDarshanRoute: typeof UjjainDarshanRoute
  VehiclesRoute: typeof VehiclesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-now': {
      id: '/book-now'
      path: '/book-now'
      fullPath: '/book-now'
      preLoaderRoute: typeof BookNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/omkareshwar': {
      id: '/omkareshwar'
      path: '/omkareshwar'
      fullPath: '/omkareshwar'
      preLoaderRoute: typeof OmkareshwarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ujjain-darshan': {
      id: '/ujjain-darshan'
      path: '/ujjain-darshan'
      fullPath: '/ujjain-darshan'
      preLoaderRoute: typeof UjjainDarshanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookNowRoute: BookNowRoute,
  ContactRoute: ContactRoute,
  OmkareshwarRoute: OmkareshwarRoute,
  ServicesRoute: ServicesRoute,
  UjjainDarshanRoute: UjjainDarshanRoute,
  VehiclesRoute: VehiclesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
